import Head from "next/head";
import styles from "@/styles/pages/Home.module.css";
import { motion, useMotionValue } from "framer-motion";
import { AnimatedText } from "@/components";
import Image from "next/image";
import { useContext, useEffect } from "react";
import { AppContext } from "./_app";
import { useRouter } from "next/router";

const Home = () => {
  const context = useContext(AppContext);
  const router = useRouter();
  const mouse = {
    x: useMotionValue(0),
    y: useMotionValue(0),
  };

  const manageMouseMovement = (e: MouseEvent) => {
    mouse.x.set(e.clientX / -35);
    mouse.y.set(e.clientY / -35);
  };

  useEffect(() => {
    window.addEventListener("mousemove", manageMouseMovement);
    return () => {
      window.removeEventListener("mousemove", manageMouseMovement);
    };
  }, []);

  return (
    <>
      <Head>
        <title>SAPHIR - HOME</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={styles.container}
        style={{
          background: context?.appColor.background,
          color: context?.appColor.text,
        }}
      >
        <motion.h1>
          <AnimatedText text="Saphir" className={styles.brand} />
          <AnimatedText text="Collection" className={styles.collection} />
        </motion.h1>
        <p>
          Issue / <span>01</span>
        </p>
        <div className={styles.image_container}>
          <motion.div
            layoutId="myImage1"
            transition={{
              layout: {
                duration: 0.8,
                ease: [0.33, 1, 0.68, 1],
              },
            }}
            style={{ x: mouse.x, y: mouse.y }}
          >
            <Image
              src="/images/1.jpg"
              alt="Saphir Collection"
              width={250}
              height={250}
              onClick={() => {
                router.push("/product/hasni");
              }}
            />
          </motion.div>
          {/* 2eme image */}
          <motion.div style={{ x: mouse.x, y: mouse.y }} layoutId="myImage2">
            <Image
              src="/images/2.jpg"
              alt="Saphir Collection"
              width={350}
              height={250}
              onClick={() => {
                context?.setAppColor({
                  background: "lightgreen",
                  text: "black",
                });
                router.push("/product/hasni");
              }}
            />
          </motion.div>

          <motion.div style={{ x: mouse.x, y: mouse.y }}>
            <Image
              src="/images/3.jpg"
              alt="Saphir Collection"
              width={150}
              height={180}
              onClick={() => {
                context?.setAppColor({
                  background: "grey",
                  text: "red",
                });
              }}
            />
          </motion.div>

          <motion.div style={{ x: mouse.x, y: mouse.y }}>
            <Image
              src="/images/4.jpg"
              alt="Saphir Collection"
              width={190}
              height={200}
              onClick={() => {
                context?.setAppColor({
                  background: "lightyellow",
                  text: "blue",
                });
              }}
            />
          </motion.div>

          <motion.div style={{ x: mouse.x, y: mouse.y }}>
            <Image
              src="/images/5.jpg"
              alt="Saphir Collection"
              width={250}
              height={250}
              onClick={() => {
                context?.setAppColor({
                  background: "lightpink",
                  text: "black",
                });
              }}
            />
          </motion.div>
        </div>
      </main>
    </>
  );
};

export default Home;
