import Head from "next/head";
import { motion, useMotionValue } from "framer-motion";
import Image from "next/image";
import { useContext, useEffect, useState } from "react";
import { Data } from "@/contract/interfaces";
import { data, hiddenMask, visibleMask } from "@/contract";
import { AnimatedText, Page } from "@/components";
import Product from "@/components/commun/Product";
import { AppContext } from "./_app";
import { getBemClassName } from "@/utils";
/*
|--------------------------------------------------------------------------
| Animation
|--------------------------------------------------------------------------
*/
const paragraph = {
  initial: { opacity: 0, y: 20 },
  animate: {
    opacity: 1,
    y: 0,
    transition: {
      delay: 1.2,
      ease: [0.5, 1, 0.89, 1],
      duration: 0.8,
    },
  },
  exit: { opacity: 0, y: 20 },
};

const imageVariants = {
  initial: { maskImage: hiddenMask },
  animate: {
    maskImage: visibleMask,
    transition: {
      duration: 0.8,
      ease: [0.33, 1, 0.68, 1],
      layoutId: { type: "spring", stiffness: 300, damping: 30 },
    },
  },
  exit: {
    maskImage: hiddenMask,
    transition: { duration: 0.3, ease: [0.5, 1, 0.89, 1] },
  },
};

/*
|--------------------------------------------------------------------------
| Style
|--------------------------------------------------------------------------
*/
const style = getBemClassName("home", [
  "main",
  "brand",
  "collection",
  "image_container",
]);
/*
|--------------------------------------------------------------------------
| Component
|--------------------------------------------------------------------------
*/
export default function Home() {
  const context = useContext(AppContext);
  const mouse = {
    x: useMotionValue(0),
    y: useMotionValue(0),
  };

  // UseEffect
  //--------------------------------------------------------------------------
  useEffect(() => {
    window.addEventListener("mousemove", manageMouseMovement);
    context?.setPlayHomeAnimation(false);
    return () => {
      window.removeEventListener("mousemove", manageMouseMovement);
    };
  }, []);

  // Methods
  //--------------------------------------------------------------------------
  const manageMouseMovement = (e: MouseEvent) => {
    mouse.x.set(e.clientX / -55);
    mouse.y.set(e.clientY / -55);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <main className={style.main}>
          <motion.h1>
            <AnimatedText text="Saphir" className={style.brand} />
            <AnimatedText text="Collection" className={style.collection} />
          </motion.h1>
          <motion.p
            variants={paragraph}
            initial="initial"
            animate="animate"
            exit="exit"
          >
            Issue / <span>01</span>
          </motion.p>
          <div className={style.image_container}>
            {data.map((item, index) => (
              <motion.div
                key={index}
                style={{ x: mouse.x, y: mouse.y }}
                variants={imageVariants}
                initial={context?.playHomeAnimation ? "initial" : "animate"}
                animate="animate"
                exit="exit"
              >
                <Image
                  src={item.image}
                  alt="Saphir Collection"
                  width={item.with}
                  height={item.height}
                  placeholder="blur"
                />
              </motion.div>
            ))}
          </div>
        </main>
      </Page>
    </>
  );
}
